# Generated by Django 6.1 on 2026-08-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intersection_id', models.CharField(max_length=50)),
                ('lane', models.CharField(max_length=20)),
                ('vehicle_count', models.PositiveIntegerField(default=0)),
                ('ambulance_detected', models.BooleanField(default=False)),
                ('signal_state', models.CharField(choices=[('green', 'Green'), ('red', 'Red'), ('off', 'Off/Skipped')], default='red', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
