# Generated by Django 6.1 on 2026-08-29 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('no_helmet', 'No Helmet'), ('triple_riding', 'Triple Riding')], max_length=20)),
                ('video_source', models.CharField(help_text='Filename of the source video/feed', max_length=255)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='violations/%Y/%m/%d/')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='accounts.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challan', to='challan.violation')),
            ],
        ),
    ]
